### ISSUE TITLE
There is wrongs when click download new JVM

### ISSUE THREAD

**Issue by Gavinin** [antelle/intellij-xcode-dark-theme#12] opened 2021-01-22 06:50 UTC
After you wanna download a new jvm ,the Vendor list will show some like quote of Class.
![1](https://user-images.githubusercontent.com/14181095/105456934-fc38f700-5cc0-11eb-8a59-60cb10ac40d4.png)
![2](https://user-images.githubusercontent.com/14181095/105456945-02c76e80-5cc1-11eb-966e-206944b1456e.png)
![3](https://user-images.githubusercontent.com/14181095/105456952-04913200-5cc1-11eb-8106-de16329887f0.png)

**Comment by antelle** [comment] 2021-01-22 06:55
Hi! Are you sure it’s caused by this theme? Does it work well if you disable it?

**Comment by Gavinin** [comment] 2021-01-25 03:53
Hi ,Unfortunity that may cause by this plugin , I tied chang to your theme
![Screenshot 2021-01-25 114701](https://user-images.githubusercontent.com/14181095/105659508-d6e7fb00-5f03-11eb-9cb8-3a5dfc624a07.png)

**Comment by antelle** [comment] 2021-01-25 06:59
Maybe I don’t understand what you mean, what happens without the theme?

**Comment by antelle** [comment] 2021-01-28 07:11
I'm going to close this, if I understand you right and what you mean is "com.intellij.api....things" being displayed instead of what you expected, this is not because of the theme, themes cannot influence this.

**Closed as completed by antelle** 2021-01-28 07:11 UTC
